name: Upload data
description: Upload data to the preassigned branch

inputs:
  branch:
    description: The branch to store the downloaded docs
    required: true
  cross-repo-token:
    description: Token to create issue in upstream repo
    required: true
  issue-title:
    description: Title of the issue to create
    required: true

runs:
  using: composite
  steps:
    - uses: stefanzweifel/git-auto-commit-action@v5
      id: commit-changes
      with:
        repository: ./docs.aws.amazon.com
        branch: ${{ inputs.branch }}
        commit_message: Update docs

    - uses: actions-ecosystem/action-create-issue@v1
      if: steps.commit-changes.outputs.changes_detected == 'true'
      with:
        github_token: ${{ inputs.cross-repo-token }}
        repo: tzing/dashify-aws-docs
        title: ${{ inputs.issue-title }}
        body: |
          Auto created issue from [aws-docs-archive].

          Branch [${{ inputs.branch }}] is updated to [${{ steps.commit-changes.outputs.commit_hash }}]

          [aws-docs-archive]: https://github.com/tzing/aws-docs-archive
          [${{ inputs.branch }}]: https://github.com/tzing/aws-docs-archive/tree/${{ inputs.branch }}
          [${{ steps.commit-changes.outputs.commit_hash }}]: https://github.com/tzing/aws-docs-archive/commit/${{ steps.commit-changes.outputs.commit_hash }}
