name: Report changes
description: Report changes to the upstream repo

inputs:
  branch:
    description: The branch to store the downloaded docs
    required: true
  cross-repo-token:
    description: Token to create issue in upstream repo
    required: true
  issue-title:
    description: Title of the issue to create
    required: true
  commit-id:
    description: The commit id of the changes
    required: true

runs:
  using: composite
  steps:
    - uses: actions-ecosystem/action-create-issue@v1
      with:
        github_token: ${{ inputs.cross-repo-token }}
        repo: tzing/dashify-aws-docs
        title: ${{ inputs.issue-title }}
        body: |
          Auto created issue from [aws-docs-archive].

          Branch [${{ inputs.branch }}] is updated to [${{ inputs.commit-id }}].

          [aws-docs-archive]: https://github.com/tzing/aws-docs-archive
          [${{ inputs.branch }}]: https://github.com/tzing/aws-docs-archive/tree/${{ inputs.branch }}
          [${{ inputs.commit-id }}]: https://github.com/tzing/aws-docs-archive/commit/${{ inputs.commit-id }}
