name: Download CloudFormation User Guide

on:
  schedule:
    - cron: "43 21 * * 4"
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/download
        with:
          branch: docs/cloudformation/user-guide
          sitemap-urls: |
            https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/sitemap.xml
            https://docs.aws.amazon.com/de_de/AWSCloudFormation/latest/UserGuide/sitemap.xml
            https://docs.aws.amazon.com/es_es/AWSCloudFormation/latest/UserGuide/sitemap.xml
            https://docs.aws.amazon.com/fr_fr/AWSCloudFormation/latest/UserGuide/sitemap.xml
            https://docs.aws.amazon.com/id_id/AWSCloudFormation/latest/UserGuide/sitemap.xml
            https://docs.aws.amazon.com/it_it/AWSCloudFormation/latest/UserGuide/sitemap.xml
            https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/sitemap.xml
            https://docs.aws.amazon.com/ko_kr/AWSCloudFormation/latest/UserGuide/sitemap.xml
            https://docs.aws.amazon.com/pt_br/AWSCloudFormation/latest/UserGuide/sitemap.xml
            https://docs.aws.amazon.com/zh_cn/AWSCloudFormation/latest/UserGuide/sitemap.xml
            https://docs.aws.amazon.com/zh_tw/AWSCloudFormation/latest/UserGuide/sitemap.xml
          cross-repo-token: ${{ secrets.CROSS_REPO_POSTER }}
          issue-title: CloudFormation user guide is updated
